name: Zeeland collectie
description: >
  This is an example pipeline. It uses files that are available in this repository 
  and SPARQL endpoints that should work.

destination: file://zeelandcollectie-linked.nt

stages:
  - name: "Stage 1"
    iterator:
      query: file://iterator-stage-1.rq
      endpoint: file://zeeuwsecollectie.nt
    generator:
      - query: file://generator-stage-1.rq
        endpoint: https://api.data.netwerkdigitaalerfgoed.nl/datasets/Fedor/Nederlandse-Bibliografie-Totaal-NBT/services/Nederlandse-Bibliografie-Totaal-NBT/sparql
        batchSize: 1000
