prefix schema: <http://schema.org/>
prefix nbt: <http://data.bibliotheken.nl/def#>
prefix owl: <http://www.w3.org/2002/07/owl#>

construct {
  $this owl:sameAs ?nbt_id .
}
where {
  ?nbt_id schema:mainEntityOfPage/nbt:ppn ?ppn_nbt
  bind(substr(str($this),26,9) as ?ppn_zb)
  filter(?ppn_nbt=?ppn_zb)
}
