prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix schema: <http://schema.org/>
prefix nbt: <http://data.bibliotheken.nl/def#>

select $this where {
  #?this schema:isPartOf <https://data.dezb.nl/id/zeelandcollectie>
  $this ?p ?o .
} limit 1000