name: AO
stages:
  - name: "Events"
    iterator:
      batchSize: 10000
      delay: 500ms
      endpoint: https://api.demo.triplydb.com/datasets/projects/colonial-heritage/sparql
      query: file://events-iterator.rq
    generator:
      - batchSize: 1000
        query: file://events-generator.rq
  - name: "Makers"
    iterator:
      batchSize: 10000
      delay: 500ms
      endpoint: https://api.demo.triplydb.com/datasets/projects/colonial-heritage/sparql
      query: file://makers-iterator.rq
    generator:
      - batchSize: 1000
        query: file://makers-generator.rq
  - name: "ObjectDates"
    iterator:
      batchSize: 10000
      delay: 500ms
      #endpoint: https://api.demo.triplydb.com/datasets/projects/colonial-heritage/sparql
      #endpoint: https://api.demo.triplydb.com/datasets/projects/colonial-heritage/services/virtuoso/sparql
      endpoint: https://api.demo.triplydb.com/datasets/projects/colonial-heritage/services/jena/sparql
      query: file://objectDates-iterator.rq
    generator:
      - batchSize: 1000
        query: file://objectDates-generator.rq
  - name: "ObjectImages"
    iterator:
      batchSize: 10000
      delay: 500ms
      endpoint: https://api.demo.triplydb.com/datasets/projects/colonial-heritage/sparql
      query: file://objectImages-iterator.rq
    generator:
      - batchSize: 1000
        query: file://objectImages-generator.rq
  - name: "ObjectLocations"
    iterator:
      batchSize: 10000
      delay: 500ms
      endpoint: https://api.demo.triplydb.com/datasets/projects/colonial-heritage/sparql
      query: file://objectLocations-iterator.rq
    generator:
      - batchSize: 1000
        query: file://objectLocations-generator.rq
  - name: "ObjectLocationDates"
    iterator:
      batchSize: 10000
      delay: 500ms
      endpoint: https://api.demo.triplydb.com/datasets/projects/colonial-heritage/sparql
      query: file://objectLocationDates-iterator.rq
    generator:
      - batchSize: 1000
        query: file://objectLocationDates-generator.rq
  - name: "Objects"
    iterator:
      batchSize: 10000
      delay: 500ms
      endpoint: https://api.demo.triplydb.com/datasets/projects/colonial-heritage/sparql
      query: file://objects-iterator.rq
    generator:
      - batchSize: 1000
        query: file://objects-generator.rq
  - name: "Sites"
    iterator:
      batchSize: 10000
      delay: 500ms
      endpoint: https://api.demo.triplydb.com/datasets/projects/colonial-heritage/sparql
      query: file://sites-iterator.rq
    generator:
      - batchSize: 1000
        query: file://sites-generator.rq
