# Metadata for your pipeline:
name: KB NBT Pipeline
description: >
  This is an example pipeline. It uses files that are available in this repository 
  and SPARQL endpoints that should work.

# The individual stages for your pipeline
stages:
  - name: "Stage 1"
    iterator:
      query: file://iterator-stage-1.rq
      endpoint: https://api.data.netwerkdigitaalerfgoed.nl/datasets/Fedor/Nederlandse-Bibliografie-Totaal-NBT/services/Nederlandse-Bibliografie-Totaal-NBT/sparql
      delay: "50ms"
      batchSize: 1000
    generator:
      - query: file://generator-stage-1.rq
        batchSize: 200
